### ISSUE TITLE
Tags icon size mismatch issue

### ISSUE THREAD

**Issue by shakil-muntasir** [siduck/chadwm#100]
So, I was trying to customize the tags icons. I tried copying icons from [Nerd Font's Cheat Sheet](https://www.nerdfonts.com/cheat-sheet) and pasting in config.def.h

However, after `sudo make install` and restarting DWM, I can see that the icons are smaller than the default one provided by you.

The default icon size is PERFECT. So, a reference to the steps you took to choose the icons would be nice.

My current fonts are:
[JetBrainsMono Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono/Ligatures)
[MaterialDesign Icons Desktop](https://github.com/Templarian/MaterialDesign-Font/blob/master/MaterialDesignIconsDesktop.ttf)

**Comment by siduck** [comment]
can you show a sceeenshot?

**Comment by shakil-muntasir** [comment]
![](https://user-images.githubusercontent.com/30091488/169681081-a1562e4e-1a04-49a0-997d-ddb8fd9f9d42.png)
Look at the third "spotify" tag icon

Step to reproduce:
Visit: [Nerd Fonts cheat sheet](https://www.nerdfonts.com/cheat-sheet)
Search: Spotify
Copy: icon with class "nf-fa-spotify"
Paste in: config.def.h
rm -f config.h && sudo make install
restart dwm

**Comment by shakil-muntasir** [comment]
![](https://user-images.githubusercontent.com/30091488/169681081-a1562e4e-1a04-49a0-997d-ddb8fd9f9d42.png)
Look at the third "spotify" tag icon

Step to reproduce:
Visit: [Nerd Fonts cheat sheet](https://www.nerdfonts.com/cheat-sheet)
Search: Spotify
Copy: icon with class "nf-fa-spotify"
Paste in: config.def.h
rm -f config.h && sudo make install
restart dwm

EDIT: Closed by mistake!

**Comment by siduck** [comment]
Do other icons copied from nerdfonts look small too?

**Comment by shakil-muntasir** [comment]
Unluckily 3-4 icons I have tried resulted the same. But copy pasting "chrome" icon was producing the same sized tag icon though.

**Comment by siduck** [comment]
idk about this, if u have a hidpi screen then make sure you set the DPI in xresources first
