### ISSUE TITLE
[Question] Padding below coloured bar

### ISSUE THREAD

**Issue by herrwusel** [siduck/chadwm#101]
How did you get the gap below the bar items?
![image](https://user-images.githubusercontent.com/8242787/170984307-d3117ffb-a8c9-455f-bffd-84566948e0f9.png)
I have currently statuspadding and status2d in my build of dwm but the block are drawn over the entire bar. Thanks :)

**Comment by siduck** [comment]
can you show how your bar looks?

**Comment by herrwusel** [comment]
Sure:
![image](https://user-images.githubusercontent.com/8242787/170987331-2e56c49a-1607-4df4-879c-2e0c16319e71.png)

**Comment by siduck** [comment]
ophh, i didnt add the inner padding inside the bar. I just added the border i think. And colored the border to the same color as bar's main bg color which creates the illusion of inner padding

**Comment by herrwusel** [comment]
Ah I see - thanks! I also found you [here](https://www.reddit.com/r/suckless/comments/on80gv/dwm_statuspadding_patch_conflicts_with_status2d/) which is helping :)
