### ISSUE TITLE
Please upgrade to 6.4

### ISSUE THREAD

**Issue by sontaimnt** [siduck/chadwm#111]
dwm 6.4 is released and take care of fibonacci , that wont run...

**Comment by siduck** [comment]
oh boi

**Comment by average-python-coder** [comment]
![image](https://user-images.githubusercontent.com/97382691/194925919-a358b4bb-4d91-463f-8748-234449824350.png)

Most of the patches worked but do u have a diif of colortags? i want it...

**Comment by siduck** [comment]
@siduck i dont have its diff, check the readme and the original dwm build from where i got the patch

**Comment by average-python-coder** [comment]
@siduck  do u have any plans to upgrade??

**Comment by siduck** [comment]
Yes but I'm a bit busy these days so I'll do it before next year for sure.

**Comment by average-python-coder** [comment]
1 month already...

**Comment by iuliandita** [comment]
> 1 month already...

you can always create a pull request, you know?

**Comment by average-python-coder** [comment]
unfortunately i dunno C and a couple of things... besides i am currently using bspwm

**Comment by iuliandita** [comment]
so why push for an update? siduck will do it when they have the time, or someone else will do a pull request, but let's have patience :)

**Comment by siduck** [comment]
> 1 month already...

if you look into dwm's git then you will find that there are no significant changes in 6.4, I will do update in this month

**Comment by alavaelian** [comment]
i love this dwm fork thanks for your work keep it up

**Comment by MinePro120** [comment]
I could make the update if you got no time @siduck.

**Comment by siduck** [comment]
sounds good @MinePro120

**Comment by siduck** [comment]
@sontaimnt done
