### ISSUE TITLE
[Request] Apply shiftview patch

### ISSUE THREAD

**Issue by MinePro120** [siduck/chadwm#112]
Hello! I really enjoy switching to the left/right tag using my arrow keys, so I was wondering if you could consider applying [this small patch](https://github.com/halhen/dwm-halhen/blob/master/patch/shiftview.patch) that enables this functionality.

_Very good work btw_

P.S. I could make a PR

**Comment by siduck** [comment]
@MinePro120 looks good! you can send a PR :)

**Comment by siduck** [comment]
oops i thought you made a PR for this, reopening
