### ISSUE TITLE
How to launch an app from the launcher

### ISSUE THREAD

**Issue by erikdubois** [siduck/chadwm#114]
I like to launch an app from the bar.

The app is called mintstick but it needs switches

`mintstick -m iso `

launches the app.

How do I realize that in dwm/chadwm? I tried a variety of possibilities.

![image](https://user-images.githubusercontent.com/10594806/202699430-3f1d16ec-87d3-43b7-a5a7-ab76ff5c5f17.png)

Ps. ArcoLinux is going to embrace chadwm and an iso with it will be created - https://arcolinux.info

**Comment by siduck** [comment]
@erikdubois did you recompile chadwm? and then reload it ( mod shift r ) then check the changes

**Comment by erikdubois** [comment]
I did

do you think the code is correct?

**Comment by siduck** [comment]
> I did
> 
> do you think the code is correct?

yes it looks correct

**Comment by MinePro120** [comment]
The correct would be:
```
static const char* mintstick[] = { "mintstick", "-m", "iso", NULL}
```
(because `execvp` is used for the launchers which requires its argument to be a null-terminated array of strings).

**Comment by erikdubois** [comment]
I can confirm that your code is correct and I thank you very much for your help.

![image](https://user-images.githubusercontent.com/10594806/202734521-2f27b9c9-330e-426b-952e-a011a5dac28c.png)
