### ISSUE TITLE
How to set mintstick.py to tiling

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#115]
I was trying to set the minstick to tiling rather than floating.

By default it wants to be floating.

I would think this would work. 6th variable to 0 means tiling - right?

`static const Rule rules[] = {
    /* xprop(1):
     *	WM_CLASS(STRING) = instance, class
     *	WM_NAME(STRING) = title
     */
    /* class      instance    title       tags mask     iscentered   isfloating   monitor */
    { "Gimp",     NULL,       NULL,       0,            0,           0,           -1 },
    { "Firefox",  NULL,       NULL,       1 << 8,       0,           0,           -1 },
    { "eww",      NULL,       NULL,       0,            0,           1,           -1 },
    { "mintstick",      NULL,       NULL,       0,            0,           1,           -1 },
};
`
Xprop shows Mintstick.py and mintstick.py in the class. I have tried that and mintstick and Mintstick. 
It will not tile whatever I put in there.
Any ideas?

Extra image because the layout is rubbish on github
![image](https://user-images.githubusercontent.com/36679406/202752117-12ea3101-a6d3-4eef-808b-db9285ed70c8.png)

Changing floating from 1 to 0 does not change the behavior.

**Comment by siduck** [comment]
tiling is the default behaviour, just remove this line 
![image](https://user-images.githubusercontent.com/59060246/202761666-45bfaecb-a800-459b-8215-c1afbefd4572.png)

**Comment by arcolinuxz** [comment]
without that line it will float

**Comment by siduck** [comment]
> without that line it will float

hmm what is ministick actually? :thinking:

**Comment by arcolinuxz** [comment]
mintstick - burns isos on a usb stick
never has failed in the last 5 years

source - https://github.com/linuxmint/mintstick

installed from AUR
https://aur.archlinux.org/packages/mintstick-git

**Comment by MinePro120** [comment]
Use `dd` to burn isos and you won't have to worry about any of this :smile:.

**Comment by MinePro120** [comment]
Switching to tiling using the provided keybinding also doesn't seem to work. Maybe have a look at Mintstick's source and change what forces this behaviour. But it probably won't look good on tiling tbh.

**Comment by arcolinuxz** [comment]
I have been on Leftwm since February 2022.
I know it is not fair to compare twms as they are not the same. Period.

This is how it looks on Leftwm - mintstick is tiled automatically.

![mintstick](https://user-images.githubusercontent.com/36679406/202906512-71d4eab1-9cc7-4d97-afba-e0dbbed2637b.png)

And here are the references in the configuration.

![mintstick2](https://user-images.githubusercontent.com/36679406/202906535-7f628225-f9f1-4f9d-82c8-52049fb4db9c.png)

And that is why I asked if I can kill an app with the right mouse click - in polybar I can do that

**Comment by siduck** [comment]
@arcolinuxz does minstick app have any wmclass?

**Comment by arcolinuxz** [comment]
result of xprop

_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 73400329, 73400330
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4600008
WM_CLIENT_LEADER(WINDOW): window id # 0x4600001
_NET_WM_PID(CARDINAL) = 455966
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "isobuilder"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified minimum size: 348 by 225
		program specified maximum size: 348 by 225
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
**WM_CLASS(STRING) = "mintstick.py", "Mintstick.py"**
WM_ICON_NAME(STRING) = "USB Image Writer"
_NET_WM_ICON_NAME(UTF8_STRING) = "USB Image Writer"
WM_NAME(STRING) = "USB Image Writer"
_NET_WM_NAME(UTF8_STRING) = "USB Image Writer"
[erik@isobuilder ~]$

**Comment by siduck** [comment]
@arcolinuxz try `xprop | grep WM_CLASS`

and show the output

**Comment by arcolinuxz** [comment]
You get the line above that is in bold...

**Comment by siduck** [comment]
oh oops, i missed it

**Comment by bakkeby** [comment]
The answer lies in the xprop output.

```
program specified minimum size: 348 by 225
program specified maximum size: 348 by 225
```

In dwm if a program's minimum size is the same as the program's maximum size then that means that the window has a fixed size which in turn means that the window should not be resized.

dwm respects those size requirements which is why the window always opens as floating. You won't get around this without tinkering.

For reference we have that the `manage` function calls `updatesizehints` which towards the end sets the `isfixed` flag for the client:

```c
c->isfixed = (c->maxw && c->maxh && c->maxw == c->minw && c->maxh == c->minh);
```

Then later in `manage` we have:
```c
    if (!c->isfloating)
        c->isfloating = c->oldstate = trans != None || c->isfixed;
```

If you wanted to remove this feature then you'd probably want to remove the line from `updatesizehints` which sets the `isfixed` flag in the first place. You may of course end up with odd behaviour in other programs that expects to have a fixed size.

**Comment by arcolinuxz** [comment]
I have lived it with it since February 2023
I think I can live with it till the day I die

Mintstick will stay floating and that is just fine with me

you can close this
