### ISSUE TITLE
Can you provide more info about the eww launcher?

### ISSUE THREAD

**Issue by erikdubois** [siduck/chadwm#116]
Here is what we see on our end?

https://youtu.be/FhpVUUaVvmQ

Are we missing packages?
Is this normal?

I read there needs to be some changes regarding audio.
Rofi pops open but closes again.

Like to learn more about the functionality of this nicely designed app.
How can it assist and improve our computing experience?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/202761095-c29593dd-8a41-4091-850a-797c42f81663.png)


I use pure alsa so i made scripts that get current volume with alsa, edit those scripts to support pulseaudio

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/202761248-65b694d2-2442-447b-92ea-5b54e0f92c2c.png)

this was the void logo ( old nerd font version ) , seems like   you are using the latest version. Just replace that icon with any other glyph

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/202761410-600b7ae0-a0d4-4c61-b9f8-8fab95331cc3.png)


material design icon fonts are needed for these icons to render

**Comment by arcolinuxz** [comment]
This is how far I got today

to do mic and headphone - I need to study where I can find that

![image](https://user-images.githubusercontent.com/36679406/202785096-69fc0d5a-41fe-4a37-864d-b1779495081d.png)

**Comment by arcolinuxz** [comment]
dmenu_run is gone and rofi is taking over
thank you for letting me fall in love again
great twm

![wow](https://user-images.githubusercontent.com/36679406/202787657-2588f453-f809-4809-bfbe-71b5111ee73d.png)

**Comment by siduck** [comment]
> This is how far I got today
> 
> to do mic and headphone - I need to study where I can find that
> 
> sticking to iosevka font - I know by experience that mixing font breaks design
> 
> ![image](https://user-images.githubusercontent.com/36679406/202785096-69fc0d5a-41fe-4a37-864d-b1779495081d.png)

looks nice, however the icons look small!

**Comment by arcolinuxz** [comment]
Icons are easily changed

explained on our channel

https://www.youtube.com/watch?v=l2-puKIAsVk

**Comment by UTFeight** [comment]
Does your terminal support utf-8 ?
Seems more like an emulator issue

**Comment by UTFeight** [comment]
I have installed Material Icons as follows:

![image](https://github.com/siduck/chadwm/assets/101834410/5c3a2588-0603-4d65-8e9a-7dd28966d805)

But seems like nothing changed?

![image](https://github.com/siduck/chadwm/assets/101834410/e73cb89c-369c-4b59-98f6-110bd8477422)

**Comment by UTFeight** [comment]
Although I did not solve my problem. I think It's because of the [breaking changes](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) that Nerd Font Developers did.

I have downgraded JetBrains Mono Nerd Font to support [logo-ls](https://github.com/Yash-Handa/logo-ls) as mentioned [here](https://github.com/Yash-Handa/logo-ls/issues/48#issuecomment-1581042300)

**Comment by siduck** [comment]
i will update the fonts soon

**Comment by siduck** [comment]
> I have installed Material Icons as follows:
> 
> ![image](https://user-images.githubusercontent.com/101834410/253044974-5c3a2588-0603-4d65-8e9a-7dd28966d805.png)
> 
> But seems like nothing changed?
> 
> ![image](https://user-images.githubusercontent.com/101834410/253045003-e73cb89c-369c-4b59-98f6-110bd8477422.png)

these wont be needed, i'll update the fonts tonight

**Comment by arcolinuxz** [comment]
close this

**Comment by siduck** [comment]
@arcolinuxz i saw your mail regarding questioning about this project getting dead or not, i previously decided to unmaintain it but now i'll just fix issues if there are any. But the DWM part is finished, i wont be adding new features to it. 

Xorg's dying day by day, i feel like it'd be more beneficial to work on wayland as its more active and has a clean codebase
