### ISSUE TITLE
Right mouse click an icon to kill the app

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#117]
Is it possible to code that a right mouse click on the icons in the bar will do a pkill discord or pkill telegram-desktop etc...

![image](https://user-images.githubusercontent.com/36679406/202789113-09555159-a6a0-4d3d-a4b0-528c665865e2.png)

**Comment by siduck** [comment]
yes it is, But i do not know much C, so I cant be of any help

**Comment by siduck** [comment]
this is the patch https://dwm.suckless.org/patches/launcher/ 

you need to add functionality for right click too

**Comment by MinePro120** [comment]
Def possible, I might make a patch that adds right click functionality.

**Comment by arcolinuxz** [comment]
would be awesome

**Comment by MinePro120** [comment]
Ok try my patch: [launchermulticlick.patch.txt](https://github.com/siduck/chadwm/files/10094559/launchermulticlick.patch.txt) (you can either `git apply launchermulticlick.patch.txt` or take a look at the patch and make the changes manually in case that doesn't work, I'm not that familiar with patches).

**Comment by siduck** [comment]
@arcolinuxz this is bloated imo so this feature wont be implemented
