### ISSUE TITLE
Chadwm does not launch from sddm

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#118]
There is one computer that will not launch chadwm from sddm.

This is the hardware info.

 https://linux-hardware.org/?probe=e3d6c78ed4

Could you also tell us what you think should be the dependencies for chadwm on Arch Linux?

the info we now have is coming from here

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chadwm-devguyahnaf-git

**Comment by arcolinuxz** [comment]
I have removed all nvidia packages from that pc thinking that would be the cause.

Nope.

still does not launch

![image](https://user-images.githubusercontent.com/36679406/202889506-1ea67185-115f-4d6e-b5f1-83daa6e01b4b.png)

**Comment by arcolinuxz** [comment]
and this is my pkgbuild

https://pastebin.com/LKB4Kmah

**Comment by siduck** [comment]
@arcolinuxz arch dependencies for chadwm https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dwm 

add imlib2

**Comment by siduck** [comment]
show chadwm.desktop, i hope you have that file in xessions folder

**Comment by arcolinuxz** [comment]
yes it is in xsessions and yes imlib2 is installed

**Comment by arcolinuxz** [comment]
I did the comparison with the package from AUR for Arch Linux

and changed these settings

https://github.com/arcolinux/arcolinux-chadwm/commit/4c03692e78001a9e67b87f3ff9b7852d7ffac859

X11 reference was wrong and not sure if I need this shape.h

https://github.com/arcolinux/arcolinux-chadwm/blob/4c03692e78001a9e67b87f3ff9b7852d7ffac859/etc/skel/.config/arco-chadwm/chadwm/dwm.c#L44

since the other package has rounded corners and I do not like that

**Comment by arcolinuxz** [comment]
Any log files I can send over... I have read the xorg log and others and nothing comes to mind
is here a specific chadwm log?

**Comment by MinePro120** [comment]
You can have a look at `~/.xsession-errors`.

**Comment by arcolinuxz** [comment]
I do not have that file... no errors?

**Comment by arcolinuxz** [comment]
Xorg logs can be looked at here
https://linux-hardware.org/?probe=e3d6c78ed4
there are several links there

**Comment by arcolinuxz** [comment]
Lets keep track of the pcs that DO run Chadwm
1. Ramins pc - https://linux-hardware.org/?probe=912f6ac7a3
2. Erik - isobuilder - https://linux-hardware.org/?probe=e3d6c78ed4

**Comment by arcolinuxz** [comment]
Figured it out.
The reason ... that is unclear

The pc that is not working needed a make and sudo make install from the .config/arco-chadwm and that solves it.
Nvidia drivers had nothing to do with it.

The other pc's have no issue with updates and the chadwm gets rebuilt but that one pc needs manual help
why is puzzling?

**Comment by siduck** [comment]
no idea @arcolinuxz , i dont use display managers so idk about sddm

**Comment by arcolinuxz** [comment]
I think/hope I found the issue
adding a switch 
make -B
and will test it now

**Comment by akibey** [comment]
@arcolinuxz, I was facing the same problem. I checked the xsessions/chadwm.desktop file. The Exec path was ~/.config/arco-chadwm/scripts/run.sh. I changed it to the complete path removing the "~" and was able to log in.

**Comment by arcolinuxz** [comment]
I solved my issue.

You need rebuild chadwm on some computers

That is what we will do for all computers now

**Comment by siduck** [comment]
> I solved my issue.
> 
> You need to rebuild chadwm on some computers
> 
> That is what we will do for all computers now

@arcolinuxz whenever you make any change in any file of chadwm's source code, you need to re-compile i.e rebuild!

**Comment by arcolinuxz** [comment]
true - but that was not the reason

we provide people an iso to install Chadwm with Calamares 

that works fine on two computers here but one reacted differently

nothing in the code was changed
