### ISSUE TITLE
Errors during make without consequences

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#119]
There is no rush. 
I am working on chadwm and loving it.

I did notice these errors.

Whenever you have time to check them out I would say.

![image](https://user-images.githubusercontent.com/36679406/202916250-f1dab268-f69b-436c-8f25-8f066ddba8fa.png)

**Comment by arcolinuxz** [comment]
I did take a look at the differences between yours and dwm 6.4.... that is a challenge
I hope you are up for it :-)

**Comment by MinePro120** [comment]
As you can clearly see, those are not errors, but warnings, nothing to worry about.
