### ISSUE TITLE
Can we get a different coloring scheme for the launchers?

### ISSUE THREAD

**Issue by erikdubois** [siduck/chadwm#121]
https://youtu.be/n_-IbvWdnkM

Making tutorials for our users I tried to apply colors to the launchers.

It seems the colors for SchemeLayout and the launcher are the same.

Can we create separate colors for the launchers or even a separate color per launcher?
![image](https://user-images.githubusercontent.com/10594806/203258075-ad939df3-28ea-48d0-944a-16b31aa72f5d.png)

**Comment by arcolinuxz** [comment]
Did I miss anything obvious?

the result is that the launcher become all black

![1](https://user-images.githubusercontent.com/36679406/203318731-3eafec6a-3394-4a2a-bec8-31fcccccd926.png)
![2](https://user-images.githubusercontent.com/36679406/203318735-fcd50c37-82df-41ca-bd2c-860021b0c50d.png)
![3](https://user-images.githubusercontent.com/36679406/203318738-2065afa4-b9ba-46c0-a2ac-fb65cebf4f2b.png)

**Comment by siduck** [comment]
@arcolinuxz you'd have to check src code for the launcher patch. I suggest you to just make a single launcher ( for rofi )  
and there are tons of rofi themes btw or make an eww widget which is also good
