### ISSUE TITLE
Can not login when zsh is the shell

### ISSUE THREAD

**Issue by erikdubois** [siduck/chadwm#122]
We discovered something strange. 

Our users were reporting they could not login.

One time it was because the /etc/locale was not correctly filled - this we understand because of past packages.

Now we discover that we can not log into Chadwm if our shell is zsh.

Can you think together with us as to what may cause this behaviour?

https://youtu.be/UgEfmtHUoLg

**Comment by MinePro120** [comment]
I use zsh and do not experience such behaviour.

**Comment by erikdubois** [comment]
I have tested it on EndeavourOS and zsh and it works fine there.

So something ... so what could it be basically?

**Comment by rainer2208** [comment]
I am on ArcoLinux and I am unable to log in with any shell. I have tried zsh, fish and bash, without avail.

**Comment by siduck** [comment]
very weird, i use mksh which is  an obscure shell, works fine here :l

**Comment by rainer2208** [comment]
> mksh

are you on Arch or ArcoLinux ?

**Comment by siduck** [comment]
> > mksh
> 
> are you on Arch or ArcoLinux ?

no i use artix linux

**Comment by rainer2208** [comment]
should I file a bug?

**Comment by siduck** [comment]
> should I file a bug?

this issue is already opened. and what is the error when you try to login? and how are you trying to login? DM or sx/startx?

**Comment by rainer2208** [comment]
i have arco linux installed and I use it with the pantheon desktop. I use lightdm as the display manager. 
when I try to log happens what you can see in Eric's video: it won't let me in and just returns to the login screen.

**Comment by siduck** [comment]
try to run it with startx

**Comment by rainer2208** [comment]
how do i that, exactly? i am not a professional, so might need a little help here ...

**Comment by siduck** [comment]
> how do i that, exactly? i am not a professional, so might need a little help here ...

go to a different tty and then run `startx ~/.config/chadwm/scripts/run.sh`

**Comment by rainer2208** [comment]
that worked ... great

**Comment by siduck** [comment]
> that worked ... great

yes, to make chadwm work with DMs, you need to make a desktop entry in the required location

**Comment by erikdubois** [comment]
not helping on ArcoLinux

**Comment by godspeed1709** [comment]
> I am on ArcoLinux and I am unable to log in with any shell. I have tried zsh, fish and bash, without avail.

Same here, I'm trying it on Archcraft

**Comment by rainer2208** [comment]
> 

i did that, the entry is in the login screen option, but i can't enter the environment, only  from a TTY with startx

**Comment by erikdubois** [comment]
I solved it yesterday for ArcoLinux 
you can close this for me

the trick for zsh is HOW you start chadwm
zsh does not like you to use  ~/.config/chadwm.... in a .desktop file

this is the commit that matters

https://github.com/arcolinux/arcolinux-chadwm/commit/33514131fe2f9df06a3b6773f11295248ace342e

**Comment by siduck** [comment]
@erikdubois what about `/home/erik/.config.... `?

**Comment by erikdubois** [comment]
see the commit

**Comment by erlan4real** [comment]
i can login into chadwm but then freeze my cursor does'nt move try to press any key but its not working
 im using kali linux ligthdm as login manager and zsh as bash

**Comment by erikdubois** [comment]
see our code

**Comment by rainer2208** [comment]
> i can login into chadwm but then freeze my cursor does'nt move try to press any key but its not working im using kali linux ligthdm as login manager and zsh as bash

@erlan4real  have you installed the wm via archlinux/ arcolinux pamac-manager ?

**Comment by arcolinuxz** [comment]
this can be closed for me - I seem to have opened it
