### ISSUE TITLE
Starting script with actual path

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#124]
How can I make this more general?

![image](https://user-images.githubusercontent.com/36679406/205447681-01c9163a-c9f3-44df-b93c-194768261c2c.png)

/home/erik/...
to
$HOME 

or something equivalent

**Comment by siduck** [comment]
does `~` work? like `~/.bin/keyhin`

**Comment by arcolinuxz** [comment]
No I have tried that before

![image](https://user-images.githubusercontent.com/36679406/206650232-a7549e23-1742-47f2-aca2-cf260799edd5.png)

**Comment by MinePro120** [comment]
Check the [getenv](https://www.tutorialspoint.com/c_standard_library/c_function_getenv.htm) function.

**Comment by arcolinuxz** [comment]
tried and failed

feeling like a noob again

**Comment by siduck** [comment]
@arcolinuxz you need to patch the source code with probably this https://dwm.suckless.org/patches/environmentvars/ 

or put that script in your path i.e put .bin folder in path 

 and then this will work
 
  `static const char* eww[] = { "keyhint", NULL };`

**Comment by siduck** [comment]
i'd go with putting the script on path
