### ISSUE TITLE
Piece of version visible

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#127]
I was wondering if you see the complete intended text what I believe should be

dwm and version of dwm-6.3

I see only this - Am I the only one that sees only part?

![image](https://user-images.githubusercontent.com/36679406/206856452-e6fde556-9bd9-4a1c-bc0c-73b18c25395f.png)

I could trace it back to this line 

![image](https://user-images.githubusercontent.com/36679406/206856408-e45cd8da-cd76-426a-9743-b92f5918076b.png)
Could you check if you can improve it?
maybe make a variable to either show it or not?

**Comment by siduck** [comment]
i think the wintitle causes this issue, do you get this issue after reverting this commit? https://github.com/siduck/chadwm/commit/9fbf88e8580b8e57688bdce3e7c0af7036f014b1

**Comment by MinePro120** [comment]
First of all, where's bar.sh @arcolinuxz? Something possibly prevents it from running. Dwm version should not be visible while bar.sh is running.

**Comment by arcolinuxz** [comment]
bar.sh is fine - this is a dual screen - in one picture the bar is on the other screen.

we did see that your bar.sh stays in the memory and when we relaunch or logout we have two bar.sh and then three bar.sh and so on

we added this code ot the run.sh

starts with 

`function run {
 if ! pgrep $1 ;
  then
    $@&
  fi
}`

and later

`
run "~/.config/arco-chadwm/scripts/bar.sh &"`

https://github.com/arcolinux/arcolinux-chadwm/blob/main/etc/skel/.config/arco-chadwm/scripts/run.sh
