### ISSUE TITLE
bar.sh keeps running

### ISSUE THREAD

**Issue by arcolinuxz** [siduck/chadwm#128]
![image](https://user-images.githubusercontent.com/36679406/206896170-5ae0cd1c-226d-4913-ba7b-45c99b287992.png)

When we logout and log back in three times we see that there are 3 instances of bar.sh

How can we overcome this?

https://github.com/arcolinux/arcolinux-chadwm/blob/709d449bb52191f88a7aa0b4b2133f56846542eb/etc/skel/.config/arco-chadwm/scripts/run.sh#L56

**Comment by arcolinuxz** [comment]
I tried so many things...

just got the idea to add

pkill bar.sh before that line and seems to work and hold

**Comment by siduck** [comment]
quit chadwm with mod shift q , it kills bar.sh. but if you quit the wm with another method then that wont kill bar.sh
