### ISSUE TITLE
feat : Perfectly centered tags 

### ISSUE THREAD

**Issue by sivaplaysmC** [siduck/chadwm#131]
With current chadwm , what you get is , 
![image](https://user-images.githubusercontent.com/89677765/210091686-a30e267a-09cb-42a7-8777-604a4d808cf4.png)
the glyphs are annoyingly off centered

with my fix , you get , 
![image](https://user-images.githubusercontent.com/89677765/210091741-ee813164-6d4f-4f8d-91a5-e9e514a9d95a.png)

@siduck  i humbly request you to add this code yourself as i am not free enough to create a PR 

for achieving this result , change line 1480 of dwm.c  from 
`drw_text(drw, x, y, w, bh_n, lrpad / 2, tags[i], urg & 1 << i); `

to 

`drw_text(drw, x + 3, 0, w, bh, lrpad / 2, tags[i], urg & 1 << i); // offset glyphs by 3 pixels `

and line 1485 of the same file from 

`        drw_rect(drw, x + ulinepad, bh_n - ulinestroke - ulinevoffset,
               w - (ulinepad * 2), ulinestroke, 1, 0);`
to 

`drw_rect(drw, x + ulinepad +3 , bh - ulinestroke - ulinevoffset,
 w - (ulinepad * 2), ulinestroke, 1, 0);  // 3 pixel padding again`

also replace line 65 in config.def.h
`static char *tags[] = {" ", " ", " ", " ", " "};`  // the tagline

**Comment by siduck** [comment]
hi @sivaplaysmC , clone latest commit and recompile. this can be more like a font issue, 

iosevka nerd font mono gives centered icon unlike iosevka nerd font

**Comment by sivaplaysmC** [comment]
my bad , i hadnt cloned the latest build ... i will try it ^_^

**Comment by sivaplaysmC** [comment]
![image](https://user-images.githubusercontent.com/89677765/210093918-0a9f2d79-1e37-4054-8053-7844a296aacd.png)
ig this is offset a bit

**Comment by sivaplaysmC** [comment]
![image](https://user-images.githubusercontent.com/89677765/210093953-73b7c61e-30b5-4902-a210-bc5340ab98ea.png)

ig this is infact offset

**Comment by siduck** [comment]
> @siduck ![image](https://user-images.githubusercontent.com/89677765/210093953-73b7c61e-30b5-4902-a210-bc5340ab98ea.png)
> 
> ig this is infact offset

that screenshot is outdated

**Comment by sivaplaysmC** [comment]
> > @siduck ![image](https://user-images.githubusercontent.com/89677765/210093953-73b7c61e-30b5-4902-a210-bc5340ab98ea.png)
> > ig this is infact offset
> 
> that screenshot is outdated

nooo that is actuall the latest build

**Comment by siduck** [comment]
oops i forgot to commit! can you check the latest commit now @sivaplaysmC
