### ISSUE TITLE
Dont now how to leave screensaver

### ISSUE THREAD

**Issue by tifasoftware** [siduck/chadwm#133]
When I click on the lavalamp icon and does that screensaver, i dont know how to exit it.

**Comment by siduck** [comment]
lavalamp icon? can you show an image?

**Comment by tifasoftware** [comment]
![2881914B-4207-4359-A946-E2B7D9EEA6F8](https://user-images.githubusercontent.com/83831269/210186640-590d77d1-e418-4a7e-9ee9-e07e9a3e06d2.jpeg)

apparently it has the wrong fonts, its this icon here

**Comment by siduck** [comment]
clicking it will run slock program, so just type your password
