### ISSUE TITLE
There is no run.sh

### ISSUE THREAD

**Issue by redc86** [siduck/chadwm#135]
?

**Comment by siduck** [comment]
https://github.com/siduck/chadwm/blob/main/scripts/run.sh

**Comment by redc86** [comment]
> https://github.com/siduck/chadwm/blob/main/scripts/run.sh

Yo how can I install this wm on archcraft this is awesome ?

**Comment by siduck** [comment]
> > https://github.com/siduck/chadwm/blob/main/scripts/run.sh
> 
> Yo how can I install this wm on archcraft this is awesome ?

read the readme of this repo!
