### ISSUE TITLE
How to configure the top bar?

### ISSUE THREAD

**Issue by rainer2208** [siduck/chadwm#136]
Hello, I am playing around with chadwm. Very a nice tool ... :-)

I could configure a lot of elements in the config file, but I am unable to add or delete elements from the right in the top bar, like the CPU or battery status .....

I found the [bar.sh](https://github.com/siduck/chadwm/blob/main/scripts/bar.sh) file , but changing anything there and compiling doesn't seem to have any visible impact.

Is this the correct file to look at?

**Comment by siduck** [comment]
@rainer2208 delete the code and then killall bar.sh file and re-run  the bar.sh file

**Comment by rainer2208** [comment]
cool, that worked perfectly, many thanks  :-)
