### ISSUE TITLE
[Question] Why are Material design icons needed?

### ISSUE THREAD

**Issue by MinePro120** [siduck/chadwm#139]
I was wondering what the Material design icons are used for. Tag icons are taken from the Nerd font and removing this font from my config, didn't seem to have any effect.

**Comment by siduck** [comment]
@MinePro120 clock and wifi icon, you can surely remove the font and replace those icons in bar.sh

**Comment by MinePro120** [comment]
Are you sure about that? Looking at the hex codes of those icons, they seem to match the ones from the Nerd fonts (search for wifi, clock [here](https://www.nerdfonts.com/cheat-sheet)).

**Comment by siduck** [comment]
@MinePro120 oops you are right, few months ago those icons werent in nerdfonts, i think they included it recently :D 

thanks for letting me know
