### ISSUE TITLE
Where's the config for the top bar widget?

### ISSUE THREAD

**Issue by musjj** [siduck/chadwm#142]
I can only find the config for the bottom right widget.

**Comment by siduck** [comment]
@musjj there's no config for it, but there's a script . check the bar.sh in scripts dir

**Comment by musjj** [comment]
@siduck I'm not really sure what I'm looking at here. Is this not eww? Or are you using something custom?
I'm not a chadwm user btw, just wanted to have your top bar.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/225197566-78ff0682-4da1-4c81-aac6-e5730e9527f7.png)

this is dwm bar @musjj

**Comment by musjj** [comment]
Ah, I'm not a dwm user :(.

**Comment by siduck** [comment]
> Ah, I'm not a dwm user :(.

btw you can do that with polybar too :v

**Comment by siduck** [comment]
look https://github.com/siduck/dotfiles
