### ISSUE TITLE
Fedora Font issues Icons won't show

### ISSUE THREAD

**Issue by KarlIsWright** [siduck/chadwm#144]
Hi! I'm trying to install this on Fedora and I'm having an issue with the icons.

![image](https://user-images.githubusercontent.com/29806650/226222276-b40ac7f1-bfc5-4266-949c-e4ae5098f42a.png)

I have installed the necessary fonts and icons so I don't know what's wrong.

`sudo dnf install -y jetbrains-mono-fonts-all`

`sudo dnf copr enable peterwu/iosevka`
`sudo dnf install -y iosevka-fonts iosevka-term-fonts`

`curl -o MaterialDesignIconsDesktop.ttf https://raw.githubusercontent.com/Templarian/MaterialDesign-Font/master/MaterialDesignIconsDesktop.ttf`

`mkdir -p /.fonts/m/`

`cp -vf MaterialDesignIconsDesktop.ttf /.fonts/m/MaterialDesignIconsDesktop.ttf`

`fc-cache -f`

`fc-scan -b ~/.fonts/m/`

When I look for the fonts in plasma font settings;
![image](https://user-images.githubusercontent.com/29806650/226222697-a1c3f493-6359-4709-a1ca-00cd3cd2f66d.png)

and in gnome
![image](https://user-images.githubusercontent.com/29806650/226223797-f8f53693-673a-4326-b25f-4799a96efecb.png)

This image was taken in Kate editor. I'm not sure if it's relevant but it can't find the font either.
![image](https://user-images.githubusercontent.com/29806650/226223675-585450fb-e1cd-4e33-860d-963332fd5eed.png)

Any Ideas why the fonts don't show?

**Comment by MinePro120** [comment]
You need a patched **Nerd** font that comes with icons (see [here](https://www.nerdfonts.com/font-downloads)). You don't need the Material Design Icons font actually.
