### ISSUE TITLE
Imlib2.h error message on Debian 11

### ISSUE THREAD

**Issue by og900aero** [siduck/chadwm#146]
I try install chadwm with readme, but I get error message:

$ sudo make install
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender -lImlib2
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA drw.c
drw.c:7:10: fatal error: Imlib2.h: No such file or directory
    7 | #include <Imlib2.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:18: drw.o] Error 1

I installed libimlib2 package, but the error is persistent.

**Comment by siduck** [comment]
install libimg2-dev
