### ISSUE TITLE
pkg_update module issue

### ISSUE THREAD

**Issue by etrigan63** [siduck/chadwm#148]
I am using chadwm on Arcolinux and I am experiencing as issue with the pkg_update module that runs in bar.sh. The module does not update periodically and when there are zero updates it shows "0 updates" instead of the stipulated "Fully Updated". The module appears to check at random intervals and only reliably on login.

**Comment by siduck** [comment]
hi @etrigan63 , can reproduce this definitely, will fix it tomorrow :)

**Comment by CharaD7** [comment]
@siduck is this issue fixed? I would be happy to provide a fix if it isn't

**Comment by siduck** [comment]
@CharaD7 go on!
