### ISSUE TITLE
Help Needed 3 Monitor Setup Left V Right Setup

### ISSUE THREAD

**Issue by thorrrr** [siduck/chadwm#155]
HI 
I need some help if possible i am using Chadwm on ArcoLinux.
I have a 3 monitor setup  i have used arandr to make a profile which when i check is the correct resolution and monitor location and setup. When I login everything is fine screen and my mouse move right to left correctly.
But when i try to move a panels to my other screen it mover opposite. So i select right it goes left and vice versa. 
I have tried changing  https://i.imgur.com/O64nhAb.png  by swapping them about but nothing works.
Please can you help me fix it i have followed all the tutorials from Arco and searched about.
So the Arco devs asked me to speak to you to see you could help[ me :)

**Comment by thorrrr** [comment]
Fixed it with a reboot

**Comment by siduck** [comment]
cool!
