### ISSUE TITLE
Getting warnings while using [make install] command

### ISSUE THREAD

**Issue by swastkk** [siduck/chadwm#157]
Getting this output while running the `sudo make install` command
```
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender -lImlib2
CC       = cc
cp config.def.h config.h
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA dwm.c
dwm.c: In function ‘arrangemon’:
dwm.c:587:3: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  587 |   strncpy(m->ltsymbol, m->lt[m->sellt]->symbol, sizeof m->ltsymbol);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dwm.c: In function ‘setlayout’:
dwm.c:2833:3: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
 2833 |   strncpy(selmon->ltsymbol, selmon->lt[selmon->sellt]->symbol,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2834 |           sizeof selmon->ltsymbol);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender -lImlib2
mkdir -p /usr/local/bin
cp -f dwm /usr/local/bin
chmod 755 /usr/local/bin/dwm
mkdir -p /usr/local/share/man/man1
sed "s/VERSION/6.4/g" < dwm.1 > /usr/local/share/man/man1/dwm.1
chmod 644 /usr/local/share/man/man1/dwm.1
```

**Comment by siduck** [comment]
@swastkk its normal, nothing to worry about

**Comment by swastkk** [comment]
Also I wanted to know that when we create the Xsessions file of `chadwm.desktop` we use the `exec` path as `Exec=/home/user/.config/chadwm/scripts/./run.sh` but shouldn't it be `/home/user/.config/chadwm/chadwm/scripts/./run.sh` since our chadwm directory is inside the chadwm repo directory?

**Comment by omansh-krishn** [comment]
Inside ~/.config/chadwm/
├── chadwm <------
│   ├── config.def.h
│   ├── config.h
│   ├── config.mk
│   ├── drw.c
│   ├── drw.h
│   ├── drw.o
│   ├── dwm
│   ├── dwm.1
│   ├── dwm.c
│   ├── dwm.o
│   ├── dwm.png
│   ├── fibonacci.c
│   ├── functions.h
│   ├── gaplessgrid.c
│   ├── Makefile
│   ├── movestack.c
│   ├── shiftview.c
│   ├── themes
│   │   ├── catppuccin.h
│   │   ├── dracula.h
│   │   ├── gruvchad.h
│   │   ├── nord.h
│   │   ├── onedark.h
│   │   └── tokyonight.h
│   ├── transient.c
│   ├── util.c
│   ├── util.h
│   ├── util.o
│   └── vanitygaps.c
├── LICENSE
├── README.md
├── rofi
│   ├── config.rasi
│   └── themes
│       ├── dracula.rasi
│       ├── everblush.rasi
│       ├── forest.rasi
│       ├── gruv.rasi
│       ├── nord.rasi
│       └── onedark.rasi
└── scripts <------------
    ├── bar.sh
    ├── bar_themes
    │   ├── catppuccin
    │   ├── dracula
    │   ├── gruvchad
    │   ├── nord
    │   ├── onedark
    │   └── tokyonight
    ├── fetch
    ├── license
    │   └── fetch.md
    └── run.sh

8 directories, 47 files
-------------------------------
chadwm directory contains one more chadwm directory in it.

**Comment by omansh-krishn** [comment]
chadwm directory contains one more chadwm directory in it.

Inside ~/.config/chadwm/
`├── chadwm <------ `
│   ├── config.def.h
│   ├── config.h
│   ├── config.mk
│   ├── drw.c
│   ├── drw.h
│   ├── drw.o
│   ├── dwm
│   ├── dwm.1
│   ├── dwm.c
│   ├── dwm.o
│   ├── dwm.png
│   ├── fibonacci.c
│   ├── functions.h
│   ├── gaplessgrid.c
│   ├── Makefile
│   ├── movestack.c
│   ├── shiftview.c
│   ├── themes
│   │   ├── catppuccin.h
│   │   ├── dracula.h
│   │   ├── gruvchad.h
│   │   ├── nord.h
│   │   ├── onedark.h
│   │   └── tokyonight.h
│   ├── transient.c
│   ├── util.c
│   ├── util.h
│   ├── util.o
│   └── vanitygaps.c
├── LICENSE
├── README.md
├── rofi
│   ├── config.rasi
│   └── themes
│   ├── dracula.rasi
│   ├── everblush.rasi
│   ├── forest.rasi
│   ├── gruv.rasi
│   ├── nord.rasi
│   └── onedark.rasi
`└── scripts <------ `
├── bar.sh
├── bar_themes
│   ├── catppuccin
│   ├── dracula
│   ├── gruvchad
│   ├── nord
│   ├── onedark
│   └── tokyonight
├── fetch
├── license
│   └── fetch.md
└── run.sh

8 directories, 47 files
