### ISSUE TITLE
Chadwm not working 

### ISSUE THREAD

**Issue by swastkk** [siduck/chadwm#158]
Followed each and every step but still it was not working, clicked on the `chadwm` sesssion in log in window then nothing happened only my laptop brand logo appears and then at same `Log in` screen, nothing else.
Please help

**Comment by siduck** [comment]
make sure you did chmod +x for the scripts/run.sh file or else try with startx

**Comment by edl2** [comment]
might be good to add that to the install instructions

**Comment by siduck** [comment]
https://github.com/siduck/chadwm/commit/f4e7fd11f4f10bb35079b00f5e7a8a7c43f10015
