### ISSUE TITLE
Hi Theme not changing when i use tokyonight

### ISSUE THREAD

**Issue by thorrrr** [siduck/chadwm#160]
HI 
I have added tokyonight to my config.def.h & bar.sh done a make- sudo make install 
This gives the following errors any idea what is wrong? 
chadwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/include/X11 -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.4" -DXINERAMA
LDFLAGS  = -L/usr/lib/X11 -lX11 -lXinerama -lfontconfig -lXft -lXrender -lImlib2 -lXext
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -O3 -march=native -I/usr/include/X11 -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.4\" -DXINERAMA dwm.c
In file included from dwm.c:413:
config.h:63:28: error: ‘pinky’ undeclared here (not in a function); did you mean ‘pink’?
   63 |     [SchemeTag6]       = { pinky,   black,  black },
      |                            ^~~~~
      |                            pink
dwm.c:1242:6: warning: ‘dragmfact’ defined but not used [-Wunused-function]
 1242 | void dragmfact(const Arg *arg) {
      |      ^~~~~~~~~
dwm.c:1168:6: warning: ‘dragcfact’ defined but not used [-Wunused-function]
 1168 | void dragcfact(const Arg *arg) {
      |      ^~~~~~~~~
make: *** [Makefile:18: dwm.o] Error 1

**Comment by siduck** [comment]
it compiled just fine for me :/ 

you probably have messed up something in config.def.h

**Comment by UTFeight** [comment]
### Quick note:

![image](https://github.com/siduck/chadwm/assets/101834410/fa1f0589-b17d-4e70-a3f1-a247cdf1ce1d)

> **Note** It's doesn't have permission to execute (`chmod +x tokyonight`) in repo
