### ISSUE TITLE
icons not loading

### ISSUE THREAD

**Issue by nbcservices** [siduck/chadwm#163]
when ever i login none of the bar icons load there is only dwm-6.4 on the left is this an issue with my internet or what else can it be

**Comment by siduck** [comment]
make sure nerdfonts are installed on system

**Comment by UTFeight** [comment]
> when ever i login none of the bar icons load there is only dwm-6.4 on the left is this an issue with my internet or what else can it be

You probably skipped `#!/bin/dash` which the `.sh` files scripted in.
Install `dash`

**Comment by utfeight** [comment]
> [!NOTE]
> After switching to NixOS, I have faced this issue even though I got the requirements I've listed in the above response.
> Main problem was doing `./bar.sh` would give me `no such file or directory` error which makes nonsense!
> Later on I've understood that It wasn't the `bar.sh` that was missing but `/bin/dash`
> thanks to NixOS's superpowers the shebang `!#/bin/dash` was causing me a missing file error
> I've fixed this problem explicitly specifying `dash` to run the script like:
> ```sh
> dash ~/.config/chadwm/scripts/bar.sh # shebang ignored
> ```
