### ISSUE TITLE
chadwm not working either through login manager or startx

### ISSUE THREAD

**Issue by MysticMaestro** [siduck/chadwm#166]
I followed all steps to get chadwm properly installed. I first tried logging in through login manager, created the desktop entry file and although I could see the "chadwm" entry on login manager screen, it reverted me back to the login screen. I tried running run.sh file through startx on a tty screen. First I got an error that .Xresources file was missing. So I copied it from the chadwm folder to the home directory but still wasn't working. I am posting my xorg log file.

https://pastebin.com/f6QNWPr7

I am using Arch linux.

**Comment by siduck** [comment]
did you chmod the run.sh file?

**Comment by MysticMaestro** [comment]
Yes, I did.

**Comment by siduck** [comment]
idk then :/ 

i hope you have compiled chadwm before

**Comment by MysticMaestro** [comment]
Yeah I compiled it. I guess my issue similar to [issue 96 ](https://github.com/siduck/chadwm/issues/96) I am also using archcraft.

**Comment by siduck** [comment]
ugh.. i'm unable to reproduce it. i just use sx ( startx alternative, startx should work too )
`alias dwm='sx sh ~/.config/chadwm/scripts/run.sh'`

**Comment by MysticMaestro** [comment]
Ok, I finally got it working. It was a locale error. To make it work, it has to be a UTF-8 locale.
Thanks for the help
