### ISSUE TITLE
Crashing after colored emojis are in browser tab

### ISSUE THREAD

**Issue by al3rez** [siduck/chadwm#175]
I'm experiencing an issue with **chadwm**. Since yesterday, certain actions like visiting specific websites or seemingly random triggers cause the following sequence:

1. The system logs out automatically.
2. My laptop's brand logo (MSI) is displayed for a few seconds.
3. I am redirected to the login screen.

Distro: Pop! OS (Ubuntu 22.04)
Laptop: MSI 17 13BV

**Comment by al3rez** [comment]
https://www.reddit.com/r/suckless/comments/11am3n3/firefox_kills_dwm/

**Comment by siduck** [comment]
@al3rez managed to fix?

**Comment by al3rez** [comment]
yup, i've if you're interested we can update the readme.

**Comment by siduck** [comment]
yes
