### ISSUE TITLE
On the tray in the upper right corner, the text is not in the center

### ISSUE THREAD

**Issue by ethercflow** [siduck/chadwm#177]
From
![image](https://github.com/siduck/chadwm/assets/38067786/622046f5-ce31-43fc-8658-9e1bf89e31c5)
we can see CPU, clock's num is not in the center.

**Comment by siduck** [comment]
mention your installed nerdfont in config.def.h 

i use iosevka for text and nerdfont for icons, check existing config.def.h font arrays*

**Comment by ethercflow** [comment]
> i use iosevka for text and nerdfont for icons, check existing config.def.h font arrays*

Thanks a lot, I found I installed wrong iosevka (I installed iosevka-nerd), after change to iosevka, it looks great!
