### ISSUE TITLE
RRRreeeeppppeeeaaaaattiiiiinnngggg    aaaa    cccchhhhaaaaarrrrraaaaccccttttteeeerrrr   wwwwiiiitthhhhouuuuuttt ddddeeeeellllaaayy

### ISSUE THREAD

**Issue by Doggo101669** [siduck/chadwm#188]
AAAAAaaasss       yyyyoooooouuuu    ccccaaann    ssseeeeee     iinnn    thhhheee     tttiiittlllleeeee,,    iiiitttt     kkkeeeeeepppssss     rrreeeeppeeeeaaaaatttiiinnngggg    ttthhhhheeee    ssssaaammmmmmeeeee   llleeeeeetttttteeeeerrrr    oooonn  aaaaannndddd    ooonnnnn   aaaaannnnndddd     oooonnn...    III''''''mmmm   nnnooottt    ssssuuuureeee  iifff  ttttthhhhhiiisss  iisssss     aaa     DDWWWWWWMMM   ppprrroobbbblleeeemmm    ooorr    CCCCHHHAAAADDDWWMM  pppprrooobbblllleeemmmm...   II    cccaaaaannnnn    nnnnooootttt    tttttyypppeeee    pppprrrroooppppeerrrrrllllyyyy   aaaassssss    yyyoooouuuu    caaaaaannnn    sssseeeeee   reeeeeaaaaaadddiiiinnnggggg    thhhhiisssssss....

**Comment by siduck** [comment]
whats up with u

**Comment by Doggo101669** [comment]
> whats up with u

RRRRReadddd    tthhheee  iiissssssssuuuee   (((IIImmm   ttyyypppeeinngg   llliikkkeee nnnnorrmmmaalll   aaannndddd   II   tthhiiiinnnkkk  iiitttsss tttooooddoooo   wwwiithhhh      tthhheee    rrrruuunn...sssh    sssccrriiipppptttt

**Comment by siduck** [comment]
thats not normal, cant reproduce this so cant help either!

**Comment by Doggo101669** [comment]
For now I am going to use i3wm until I find a fix or someone finds a fix.

**Comment by siduck** [comment]
haha no! btw you can remove the xset stuff too, i only use it as it increases the input speed i think, like moving curser/typing speed etc  

idk its actual usage, got it from lunarvim's creator

**Comment by Subhashis2007** [comment]
> It just changes the delay between spamming when you hold, and the rate of it. (on keyboard)

lmao u could have created the issue using another device or may be ur phone
