### ISSUE TITLE
which eww widget is this.

### ISSUE THREAD

**Issue by mrlinuxdude** [siduck/chadwm#195]
hi
can you tell me which eww widget in 5 screenshot. The cool void logo and type dashboard. Which script is it. I really love it Thanks

**Comment by siduck** [comment]
https://github.com/siduck/chadwm/tree/main/eww

sadly i dont use it anymore and eww has changed a lot so there might be some visual glitches

**Comment by mrlinuxdude** [comment]
Do you still have it in your repo?  if you know what its called

**Comment by siduck** [comment]
> https://github.com/siduck/chadwm/tree/main/eww

https://github.com/siduck/chadwm/tree/main/eww

**Comment by mrlinuxdude** [comment]
this launcher?
https://i.imgur.com/lubgh13.png

**Comment by siduck** [comment]
> this launcher? https://i.imgur.com/lubgh13.png

yes

**Comment by mrlinuxdude** [comment]
What is the name of it. in eww folder?

**Comment by siduck** [comment]
> What is the name of it. in eww folder?

the eww folder itself, to use the eww widget, i hope you know eww basics

**Comment by mrlinuxdude** [comment]
https://i.imgur.com/lubgh13.png this launcher what is name of it in your eww FOLDER?

**Comment by siduck** [comment]
yes

**Comment by mrlinuxdude** [comment]
I tried it!.. i didn't get that in the screenshot. Whats the name of it in the folder
https://i.imgur.com/lubgh13.png

**Comment by siduck** [comment]
you should know how to start a eww widget if its dir exists

you can just move the eww dir to ~/.config/ and then run `eww open eww`

or eww -c /path... open eww

**Comment by mrlinuxdude** [comment]
I'm not asking how to start eww. 
can you just tell me the name of this eww https://i.imgur.com/lubgh13.png widget? if don't want share it that's fine too

**Comment by siduck** [comment]
that is in the chadwm repo itself!!!!!!!!!! the eww folder
