### ISSUE TITLE
Wrong Focused Window Border comment

### ISSUE THREAD

**Issue by alokshandilya** [siduck/chadwm#51]
Thanks for your chadwm, looks great.
While I was trying to tweak nord, gruvchad colorscheme header file, I found that blue[ ] has been commented as focused window border.
But changing gray4[ ] changes the focused window border.

**Comment by chown-coffee** [comment]
Hello! So, i don't know if you solved the problem already, but here is the explanation and solution:
The actual color scheme referred to the focus and unfocused window is this tag:
```[SchemeSel]```

You can find it in `config.def.h` file inside the `*colors[][3]` variable. If you pay attention in there, you may see that both the foreground and the border are defined as `gray4`.  Here is how it looks like in the code:

```
                // fg   // bg  // border (the one that should be blue)
*[SchemeSel] = { gray4, blue,  gray4  },*
```
So, to "solve" this you simply need to change the third value from gray4 to blue, or to any color you want to be the border scheme.

**Comment by siduck** [comment]
@alokshandilya oh sorry that was intended! I made that change for myself but mistakenly commited it.
