### ISSUE TITLE
dash as dependency

### ISSUE THREAD

**Issue by alokshandilya** [siduck/chadwm#52]
The bar wasn't working for me , installing `dash` solved that issue.
I think in requirements  in README `dash` can be added

**Comment by peppapig450** [comment]
Maybe change it to #!/bin/sh? Isnt dash only the default posix on ubuntu/debian forks?

**Comment by siduck** [comment]
> Maybe change it to #!/bin/sh? Isnt dash only the default posix on ubuntu/debian forks?

yes , on void too but ig not all distros! some might use bash by default I think , bash takes like 10x more ram for the bar than the current dash script. dash : 300kb ~ and bash 3mb+ . So i moved the bar script to dash

**Comment by siduck** [comment]
> The bar wasn't working for me , installing `dash` solved that issue. I think in requirements in README `dash` can be added

https://github.com/siduck/chadwm/commit/7d9564c7bfa7483c0437232a617d848f786a5b17

**Comment by peppapig450** [comment]
was that bash in in posix mode? or normal bash?

**Comment by peppapig450** [comment]
you can put #!/bin/bash and do set -o posix at the top

**Comment by peppapig450** [comment]
/bin/sh symlinked to bash seems to be just barely slower than dash but i dont know how to time it to get the exact time

**Comment by siduck** [comment]
> was that bash in in posix mode? or normal bash?

normal bash
