### ISSUE TITLE
I cant open terminal

### ISSUE THREAD

**Issue by YeetusDelitus** [siduck/chadwm#57]
Hello i followed instructions and now i have just the bar and black screen for background as far as i understand i need to change config file but i cant even open my terminal emulator(kitty).I tried win+enter didnt work and a couple of others.How can i fix this?

**Comment by siduck** [comment]
to set kitty you need to replace the word st in config.def.h and the for the black background , thats cuz you dont have any wallpaper set. go to your ~/.dwm/autostart file and edit it.

**Comment by YeetusDelitus** [comment]
I did it for background but i dont understand what do you mean by replacing the word st.Do you mean to replace it with kitty or some other word and also where is that word in config file?

**Comment by siduck** [comment]
> I did it for background but i dont understand what do you mean by replacing the word st.Do you mean to replace it with kitty or some other word and also where is that word in config file?

chadwm/chadwm dir

**Comment by siduck** [comment]
termcmd probably , are you new to wms?

**Comment by YeetusDelitus** [comment]
Yeah i am pretty  new to all this wm stuff but now it works so thank you
