### ISSUE TITLE
Eww doesnt work

### ISSUE THREAD

**Issue by YeetusDelitus** [siduck/chadwm#58]
I install eww and copied your eww files to .config and start eww but nothing happend.Am i missing something?

**Comment by siduck** [comment]
eww open alsa-gui ,btw it will work only if you use alsa in your system. most people use pulseaudio

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/146697516-95fee6fc-cb83-40f2-b1f2-febca1593c2f.png)

basically eww open windowname

**Comment by YeetusDelitus** [comment]
Ok thank you.
