### ISSUE TITLE
Question about the rounded corners in the bar.

### ISSUE THREAD

**Issue by joaoofreitas** [siduck/chadwm#59]
_Hello!_

I'm sorry to ask you, because probably someone has already asked you this before but...

What patch did you added to the bar to create the rounded corners? _Asking for a friend..._

Thanks!

**Comment by siduck** [comment]
There aren't any rounded corners!

**Comment by joaoofreitas** [comment]
Ohhh, I could swear there was! It's so clean.

Congrats for the rice.
Closing this rice.

**Comment by siduck** [comment]
@joaoofreitas  rounded corners on any wm is pretty easy! install picom-ibhagwan (fork of picom) and add this in your picom.conf

```
corner-radius : 10
```

**Comment by joaoofreitas** [comment]
> @joaoofreitas rounded corners on any wm is pretty easy! install picom-ibhagwan (fork of picom) and add this in your picom.conf
> 
> ```
> corner-radius : 10
> ```
> 
> make sure that picom is running :)

I use the normal picom! Gotta give it a try! 
Thanks for your contribution!

_Cheers_
