### ISSUE TITLE
Remove bar padding?

### ISSUE THREAD

**Issue by AlphaTechnolog** [siduck/chadwm#60]
How I can remove the bar margin from the screen:

![Screenshot from 2022-01-20 18-33-27](https://user-images.githubusercontent.com/54639968/150432877-03e8fbfc-779a-4fad-a3db-730c908e3efd.png)

> How remove the it bar margin from the screen?

**Comment by siduck** [comment]
https://github.com/siduck/chadwm/issues/21
https://github.com/siduck/chadwm/issues/22

**Comment by AlphaTechnolog** [comment]
Thank you so much @siduck good work with Chadwm, I love ti!
