### ISSUE TITLE
cant run a program with keybindings

### ISSUE THREAD

**Issue by Golam-moula** [siduck/chadwm#62]
Alt + p would toggle dmenu in dwm
but as u modified the shortcuts i cant run anything without a terminal

**Comment by siduck** [comment]
> Alt + p would toggle dmenu in dwm but as u modified the shortcuts i cant run anything without a terminal

add that keybind then, I removed some of the basic dwm keybinds. I use rofi ( mod + c )

**Comment by Golam-moula** [comment]
thanks
