### ISSUE TITLE
Help in configuring chadwm

### ISSUE THREAD

**Issue by AnishKacham** [siduck/chadwm#65]
Hello. I'm kinda new to arch and dwm.
I followed the instructions in the Readme, But it still quite doesn't look like in the screenshots. For example the status in the dwmbar still shows "dwm-6.2" instead of the ones in the screenshot. Am I supposed to be doing something further?

**Comment by siduck** [comment]
do you even have xsetroot installed :/

**Comment by AnishKacham** [comment]
yeah. I have xorg-xsetroot installed.

**Comment by siduck** [comment]
run bar.sh from terminal and see error

**Comment by AnishKacham** [comment]
It outputs the following :
```
bar.sh: line 19: doas: command not found
cat: /sys/class/power_supply/BAT1/capacity: No such file or directory
cat: /sys/class/power_supply/BAT1/capacity: No such file or directory
```
and keeps running until I quit.

**Comment by siduck** [comment]
yea change BAT1 to your battery adapter name in bar.sh and edit update function ( xbps ) if you dont use void

**Comment by AnishKacham** [comment]
Thank you. I figured out what was wrong. dwm was executing an extra time in my .xinitrc that was messing up stuff.
