### ISSUE TITLE
How do I disable the cursor expanding?

### ISSUE THREAD

**Issue by nuclearbomb404** [siduck/chadwm#66]
My cursor becomes way too big whenever it is inside specific windows. (vscode, firefox, etc.) How do i disable this in the code?

**Comment by siduck** [comment]
i dont think dwm handles that

**Comment by nuclearbomb404** [comment]
oh ok

**Comment by nuclearbomb404** [comment]
NVM the cursor size setting was in ~/.config/gtk-3.0/settings.ini

**Comment by siduck** [comment]
> NVM the cursor size setting was in ~/.config/gtk-3.0/settings.ini

I use lxappearance for setting gtk,icon,cursor. So should u!
