### ISSUE TITLE
How can I change the position of the tag previews?

### ISSUE THREAD

**Issue by EnxGitHub** [siduck/chadwm#70]
I want them a little bit lower.

**Comment by siduck** [comment]
> I want them a little bit lower.

you might have to edit the src code

**Comment by EnxGitHub** [comment]
I tried that but I wasnt successful
After adding 50 like this:
`imlib_render_image_part_on_drawable_at_size(0, 0, selmon->mw, selmon->mh, 0, 50, selmon->mw / scalepreview, selmon->mh / scalepreview);`
The preview became like this:
![image](https://user-images.githubusercontent.com/65719051/155003192-35dfd89f-f4c7-49ce-958b-83c7ea03adfe.png)

**Comment by baizeyv** [comment]
> I tried that but I wasnt successful
> After adding 50 like this:
> `imlib_render_image_part_on_drawable_at_size(0, 0, selmon->mw, selmon->mh, 0, 50, selmon->mw / scalepreview, selmon->mh / scalepreview);`
> The preview became like this:
> ![image](https://user-images.githubusercontent.com/65719051/155003192-35dfd89f-f4c7-49ce-958b-83c7ea03adfe.png)
> 
Maybe you can change the 'XCreateWindow' line in the function 'updatepreview'

**Comment by EnxGitHub** [comment]
Thanks

I changed this:
`m->tagwin = XCreateWindow(dpy, root, m->wx, m->by + bh, m->mw / scalepreview, m->mh / scalepreview, 0,
								  DefaultDepth(dpy, screen), CopyFromParent, DefaultVisual(dpy, screen),
								  CWOverrideRedirect | CWBackPixmap | CWEventMask, &wa);`

to this:
`m->tagwin = XCreateWindow(dpy, root, m->wx, m->by + bh + 10, m->mw / scalepreview, m->mh / scalepreview, 0,
								  DefaultDepth(dpy, screen), CopyFromParent, DefaultVisual(dpy, screen),
								  CWOverrideRedirect | CWBackPixmap | CWEventMask, &wa);`
