### ISSUE TITLE
i need help to configure chadwm

### ISSUE THREAD

**Issue by alavaelian** [siduck/chadwm#72]
a more detailed guide to install and theming chadwm would be great

**Comment by siduck** [comment]
sudo make install?

**Comment by alavaelian** [comment]
> sudo make install?

yes but i still dont get it fully working with eww and rofi

**Comment by siduck** [comment]
> > sudo make install?
> 
> yes but i still dont get it fully working with eww and rofi

did u copy eww / rofi in config dir? and eww open eww is the command to open it. you need to edit some  parts in the scripts for your hardware like wifi adapter , battery ,   distro package count etc

**Comment by alavaelian** [comment]
i need to know how to add see the dwm shortcuts  to configure the terminal and eww shortcut

**Comment by alavaelian** [comment]
> > > sudo make install?
> > 
> > 
> > yes but i still dont get it fully working with eww and rofi
> 
> did u copy eww / rofi in config dir? and eww open eww is the command to open it. you need to edit some parts in the scripts for your hardware like wifi adapter , battery , distro package count etc and install proper fonts!

thanks so much for answare mate

**Comment by siduck** [comment]
> i need to know how to add see the dwm shortcuts to configure the terminal and eww shortcut

have you used dwm before?

**Comment by alavaelian** [comment]
> > i need to know how to add see the dwm shortcuts to configure the terminal and eww shortcut
> 
> have you used dwm before?

yes man

**Comment by siduck** [comment]
> > > i need to know how to add see the dwm shortcuts to configure the terminal and eww shortcut
> > 
> > 
> > have you used dwm before?
> 
> yes man

then you show know how dwm keybindings work!

**Comment by alavaelian** [comment]
> > > > i need to know how to add see the dwm shortcuts to configure the terminal and eww shortcut
> > > 
> > > 
> > > have you used dwm before?
> > 
> > 
> > yes man
> 
> then you show know how dwm keybindings work!

again thanks for answer i get one more issue where i can change the font in the bar (i mean in the icos) they got very small when i instaled a font

**Comment by siduck** [comment]
> > > > > i need to know how to add see the dwm shortcuts to configure the terminal and eww shortcut
> > > > 
> > > > 
> > > > have you used dwm before?
> > > 
> > > 
> > > yes man
> > 
> > 
> > then you show know how dwm keybindings work!
> 
> again thanks for answer i get one more issue where i can change the font in the bar (i mean in the icos) they got very small when i instaled a font

font varible in config.def.h ._.

**Comment by alavaelian** [comment]
which are the layouts shortcuts ?

**Comment by HassanGamer69** [comment]
> > > sudo make install?
> > 
> > 
> > yes but i still dont get it fully working with eww and rofi
> 
> did u copy eww / rofi in config dir? and eww open eww is the command to open it. you need to edit some parts in the scripts for your hardware like wifi adapter , battery , distro package count etc and install proper fonts!

sorry for late reply, but "eww open" needs some parameters to work. may I see some?

**Comment by siduck** [comment]
eww open eww command :/

**Comment by HassanGamer69** [comment]
> eww open eww command :/

thanks a bunch, all the guides I've seen so far are passing window names after "eww open"

**Comment by siduck** [comment]
yes , eww open windowname, in our case 'eww' is the window name, check eww.yuck file

**Comment by Bwangp** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/156330921-86c97991-8944-4b3c-8c17-4222480937b5.png)
> 
> read the config.def.h

What bar is it?

**Comment by siduck** [comment]
@Bwangp  that was tint2 but ive been  using eww bar for 2 years now

<img width="1852" height="97" alt="Image" src="https://github.com/user-attachments/assets/51b08c47-2a16-4e25-b952-6e6d7906190d" />

**Comment by Bwangp** [comment]
> [@Bwangp](https://github.com/Bwangp) that was tint2 but ive been using eww bar for 2 years now
> <img alt="Image" width="1852" height="97" src="https://private-user-images.githubusercontent.com/59060246/467871358-51b08c47-2a16-4e25-b952-6e6d7906190d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMwODY4MDksIm5iZiI6MTc1MzA4NjUwOSwicGF0aCI6Ii81OTA2MDI0Ni80Njc4NzEzNTgtNTFiMDhjNDctMmExNi00ZTI1LWI5NTItNmU2ZDc5MDYxOTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIxVDA4MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YTA2YjYwOGUwMGFlMTg1ZmMwY2RkNDRhZTZkMGRlYzJjMzRiYjYyYzgwNTNjYTAyY2RiYjlkMDZmNWM0YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2cK6fIIP2LZph8kwF1ku_0GGQv25jaJvgiD24toQMzg">

Thanks you very much
