### ISSUE TITLE
chadwm crash if you have more than 7 workspaces 

### ISSUE THREAD

**Issue by JoaoVictorRosmaninho** [siduck/chadwm#78]
if you have more than 7 workspaces  and try open a application in a workspace >= 7 the chadwm just crash

**Comment by JoaoVictorRosmaninho** [comment]
the problem occurs because there is only 5 schemes of colors defined, the solutions is set more color schemes or use the ones already defined
![2022-03-13-18:50:08-screenshot](https://user-images.githubusercontent.com/31747455/158080703-7614f17c-7603-4be2-963f-1c2cd66b1c4a.jpg)

**Comment by siduck** [comment]
> the problem occurs because there is only 5 schemes of colors defined, the solutions is set more color schemes or use the ones already defined ![2022-03-13-18:50:08-screenshot](https://user-images.githubusercontent.com/31747455/158080703-7614f17c-7603-4be2-963f-1c2cd66b1c4a.jpg)

great!
