### ISSUE TITLE
How to add more tags?

### ISSUE THREAD

**Issue by DaereanLegrand** [siduck/chadwm#79]
I tried editing config.def.h and adding tags to the variable *tags, but each time i open a window in a different tag, dwm crashes. Help please.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/158495846-9b57a949-8ed6-47cd-a3e2-a07451bbec18.png)
https://github.com/siduck/chadwm/issues/78

**Comment by siduck** [comment]
basically u just need to define more colors in tagschemes

**Comment by DaereanLegrand** [comment]
ohh thx sorry
