### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by subnut** [siduck/chadwm#81]
In [this](https://camo.githubusercontent.com/cecb8bf60d888e57618495f23392d02343e2fd0773099a7dcdfcfd0efb93d621/68747470733a2f2f692e726564642e69742f743170766d716c71336f6338312e706e67) screenshot
- What is the font being used?
- What is the file previewer that is being shown in the 3rd screenshot?

**Comment by siduck** [comment]
jetbrainsmono and telescope.nvim is the previewer . its a nvim plugin and check my nvchad repo :D
