### ISSUE TITLE
Doesn't work properly

### ISSUE THREAD

**Issue by JekiTheMonkey** [siduck/chadwm#87]
I followed everything that's said in `Setup` section but this DWM doesn't work. What I mean by that is that it opens, all the key bindings work as usual, but no new graphical elements appear, my status bar is full of emoji codes, I guess, like ^c#BF616A^ with some values in between, such as 1.5G (I guess that's used RAM), time and such.

I've installed `dash`, `imlib2`, `xsetroot` and moved all the fonts from `Fonts` directory to `~/.local/share/fonts`, and then I've `sudo make install`ed the program, that's all. To open I do `xstartx`, I know that I can put it in xinitrc though.

What should I do?

**Comment by siduck** [comment]
show the image of the bar

**Comment by siduck** [comment]
show the output when running bar.sh

**Comment by JekiTheMonkey** [comment]
The bar
https://ibb.co/rQYdSQ5

bar.sh gives me
```
.bar.sh: 19: doas: not found
cat: /sys/class/power_supply/BAT1/capacity: No such file or directory
```

**Comment by siduck** [comment]
install opendoas

**Comment by siduck** [comment]
and edit the battery function too

**Comment by JekiTheMonkey** [comment]
Do I need to recompile after I install opendoas?

**Comment by siduck** [comment]
no

**Comment by JekiTheMonkey** [comment]
Now I have an empty bar, just the tags, opened window and `dwm-6.2` at the top right corner, nothing else

**Comment by JekiTheMonkey** [comment]
I tried to run `bar.sh` myself and it asked for my password, once entered it it ran the thing, gave me `doas: xbps-install:command not found` and now I have the same result, the bar full of "junk"

**Comment by JekiTheMonkey** [comment]
After installing `xbps` it silently runs, but the bar looks the same way

**Comment by siduck** [comment]
> I tried to run `bar.sh` myself and it asked for my password, once entered it it ran the thing, gave me `doas: xbps-install:command not found` and now I have the same result, the bar full of "junk"

if you dont use void then edit that function for your distro.

**Comment by siduck** [comment]
> The bar https://ibb.co/rQYdSQ5
> 
> bar.sh gives me
> 
> ```
> .bar.sh: 19: doas: not found
> cat: /sys/class/power_supply/BAT1/capacity: No such file or directory
> ```

this too, your battery adapter isnt BAT1 so edit that too bruh

**Comment by JekiTheMonkey** [comment]
> > I tried to run `bar.sh` myself and it asked for my password, once entered it it ran the thing, gave me `doas: xbps-install:command not found` and now I have the same result, the bar full of "junk"
> 
> if you dont use void then edit that function for your distro.

I'm using Arch, and to set anything to the DWM bar `xsetroot -name` is used. I think the problem is in regards to the fonts since the emojies basically don't render

**Comment by siduck** [comment]
> > > I tried to run `bar.sh` myself and it asked for my password, once entered it it ran the thing, gave me `doas: xbps-install:command not found` and now I have the same result, the bar full of "junk"
> > 
> > 
> > if you dont use void then edit that function for your distro.
> 
> I'm using Arch, and to set anything to the DWM bar `xsetroot -name` is used. I think the problem is in regards to the fonts since the emojies basically don't render

 chadwm doesnt set any emojis by default but if u add them to the bar then install libxft-bgra from aur

**Comment by JekiTheMonkey** [comment]
> > > > I tried to run `bar.sh` myself and it asked for my password, once entered it it ran the thing, gave me `doas: xbps-install:command not found` and now I have the same result, the bar full of "junk"
> > > 
> > > 
> > > if you dont use void then edit that function for your distro.
> > 
> > 
> > I'm using Arch, and to set anything to the DWM bar `xsetroot -name` is used. I think the problem is in regards to the fonts since the emojies basically don't render
> 
> chadwm doesnt set any emojis by default but if u add them to the bar then install libxft-bgra from aur

Doesn't it set them at the top right angle? Like updates, CPU&RAM usage, time.
BTW I resolved the issue. Apparently chadwm tried to execute a dwm, but for some reason I had my old also in `~/.local/bin`, and chadwm ran the old one instead
