### ISSUE TITLE
Where can i get the icon for workspace?

### ISSUE THREAD

**Issue by LudovicoSforza** [siduck/chadwm#88]
i use icon from nerdfont cheat sheet but it seems so small in my bar.
![Screenshot_2022-04-13-09-09-15_1366x768](https://user-images.githubusercontent.com/44255157/163199576-dbfa01ea-4051-4792-9df5-bab3e2bc9cdc.png)

**Comment by siduck** [comment]
they look fine, just dont use small icons like the terminal one

**Comment by LudovicoSforza** [comment]
Allright, thanks for your quick response!
