### ISSUE TITLE
how to unpatch notitle

### ISSUE THREAD

**Issue by ItzSelenux** [siduck/chadwm#89]
Hi, your DWM mod is very cool, but i wonder if is possible to unpatch notitle because i need title, i tried ` git apply -R` but doesn't work

**Comment by siduck** [comment]
notile patch? I dont think i added it

**Comment by siduck** [comment]
ohh this? https://dwm.suckless.org/patches/notitle/dwm-notitle-6.2.diff , manually patch it

**Comment by ItzSelenux** [comment]
yes, is that, but is not a way to have again windows title?

**Comment by siduck** [comment]
remove that patch manually, patch -R < file wont work automatically as there are many conflicts
