### ISSUE TITLE
[Request] Apply dwm-swallow patch

### ISSUE THREAD

**Issue by KlemensMaentele** [siduck/chadwm#92]
Add dwm-swallow patch
(Luke Smith on dwm-swallow): "DWM has a somewhat unique patch called swallow which automatically positions a window opened from a terminal over that terminal that would otherwise be non-responsive, uncloseable and thus a big annoyance."
It really is a handy patch but I wasn't able to patch it due to my lack of skill and experience with patching.
Patch: https://dwm.suckless.org/patches/swallow/

**Comment by KlemensMaentele** [comment]
https://www.youtube.com/watch?v=92uo5OBOKfY

**Comment by igorcguedes** [comment]
That looks a nice feature.

**Comment by siduck** [comment]
alright i will try to patch it this weekend
