### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by LittleQuartZ** [siduck/chadwm#93]
I can't figure out how to use this chadwm, it works only in Xephyr, not in SDDM or xinit (startx). my .xinitrc file and chadwm.desktop file is the same with the one provided in readme. running bar.sh returns no error, autostart have one expected error which is `dwm: another window manager is already running`

#### Screenshot of Xephyr

![Screenshot_2022-05-01-11-58-47_1920x1080](https://user-images.githubusercontent.com/58659387/166156478-c68476b0-da4e-4525-98d5-105ceca42a2e.png)

**Comment by siduck** [comment]
show your xinitrc

**Comment by LittleQuartZ** [comment]
`#!/bin/sh
exec ~/.config/chadwm/scripts/./autostart`

**Comment by siduck** [comment]
did u chmod +x all the scripts in chadwm dir?
show your autostart too

**Comment by LittleQuartZ** [comment]
![image](https://user-images.githubusercontent.com/58659387/166157113-c75df1fe-d92c-469d-9b46-12140f518ca0.png)

**Comment by siduck** [comment]
when you are in tty, run startx

**Comment by LittleQuartZ** [comment]
..bruh i didn't even change anything and this suddenly works
![image](https://user-images.githubusercontent.com/58659387/166157961-7792c67c-1866-46d1-8816-8048b183528c.png)

**Comment by LittleQuartZ** [comment]
still not working on sddm, and bar is flickering on pkg update and battery

**Comment by siduck** [comment]
thats because you have to change update function to fit your distro, mine is void so it will work ootb bruh. Also change adapter name in battey function of bar.sh . Please read bar.sh or run it in cli to get errors and fix those :c

**Comment by LittleQuartZ** [comment]
> thats because you have to change update function to fit your distro, mine is void so it will work ootb bruh. Also change adapter name in battey function of bar.sh . Please read bar.sh or run it in cli to get errors and fix those :c

adapter name changed, update function is set to arch, pacman contrib installed, running bar.sh returns no error.

it is showed but flickering

**Comment by LittleQuartZ** [comment]
https://user-images.githubusercontent.com/58659387/166159048-714ca39d-afbd-4ae1-b3e4-1512e4b6f7cd.mp4

screen record of bar

**Comment by golam47** [comment]
there are two process running that have 
xsetroot -name "something"
one of theme is bar.sh but u have ro figure out what the other process is then u have to kill it use htop

**Comment by siduck** [comment]
yea that seems like it

**Comment by LittleQuartZ** [comment]
and for .desktop in SDDM ?

**Comment by siduck** [comment]
idk about sddm so cant help

**Comment by LittleQuartZ** [comment]
okay, thanks for helping me, love your works

**Comment by siduck** [comment]
if you're using xorg then make the desktop file at /usr/share/xessions/chadwm.desktop

**Comment by LittleQuartZ** [comment]
i am using xorg, with SDDM

im sorry i don't get what you mean, btw im enjoying this very well, everything works this time

**Comment by LittleQuartZ** [comment]
welp, i just managed to get it working
use `Exec=/home/user/.config/chadwm/scripts/./autostart`
