### ISSUE TITLE
Terminal font

### ISSUE THREAD

**Issue by limeless** [siduck/chadwm#98]
![image](https://user-images.githubusercontent.com/1501022/169664706-fcf78a92-f722-4ac0-a5a0-412f10565587.png)

I really love this font draws line instead of ⣿, may I ask what font is being used?

Thanks.

**Comment by siduck** [comment]
its jetbrainsmono nerd font

**Comment by limeless** [comment]
I am using the same font but it doesn't draw lines.
Can you kindly share your st config? Thanks.

**Comment by siduck** [comment]
> I am using the same font but it doesn't draw lines. Can you kindly share your st config? Thanks.

it doesnt draw lines? wym, you mean ligatures?

**Comment by siduck** [comment]
check my st repo!

**Comment by limeless** [comment]
Thank you so much for your config,
it turns out it's my st problem, after install your verison it draws blocks instead of braille.


> check my st repo!
