### ISSUE TITLE
Failed to run st with SUPER+RETURN

### ISSUE THREAD

**Issue by shakil-muntasir** [siduck/chadwm#99]
With the latest commit, config.def.h shows that SUPER+RETURN will execute "st_pad && st"
I can comment this out and fix the issue by execute "st" instead of "st_pad && st"

But actual question is, what this "st_pad" refers to? Is it useful? reference to installer/documentation would help.

**Comment by siduck** [comment]
oops i messed with that, st_pad is a script I made for dynamic padding in st with/without neovim windows
